### ISSUE TITLE
Order price is incorrect

### ISSUE THREAD

**Issue by gjunkie** [jazznov/opal-coding-exercise#1]
Starting with a brand new order, I pressed the _up_ arrow to add 1 hamburger. The unit cost is set to $4.50, but my order total is $15.25 for some reason.

I then added a bunch of hamburgers and noticed that the price will always be $15.25.

Looks like the total price for the order is always showing as if I had added a single item of each type.

![screen shot 2017-09-05 at 4 33 35 pm](https://user-images.githubusercontent.com/626628/30087920-46a12998-9258-11e7-885f-3ec666b5d9df.png)

**Comment by jazznov** [comment]
Thanks for catching this. Should be fixed now!
