### ISSUE TITLE
Canceling an order will cancel all other orders instead

### ISSUE THREAD

**Issue by gjunkie** [jazznov/opal-coding-exercise#2]
I created a few open orders, all of which were visible on the order list on the left. I then selected one of them and chose to cancel it. Instead of that order being canceled, it instead cancelled all other orders and left the one I meant to cancel open.

Further, you cannot cancel the last order on the list. I suspect this is related, as it is probably trying to cancel all other orders instead.

Closing an order removes the correct one.

**Comment by jazznov** [comment]
Hey, thanks for diagnosing this, @gjunkie. Should be taken care of now!
